# Generated by Django 5.0.2 on 2024-02-23 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appareil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name="Nom de l'appareil ")),
                ('description', models.TextField(max_length='500', verbose_name="Description de l'appareil")),
            ],
            options={
                'verbose_name_plural': 'Appareils',
                'db_table': 'Appareil',
            },
        ),
        migrations.CreateModel(
            name='Hopital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name="Nom de l'hopital ")),
            ],
            options={
                'verbose_name_plural': 'Hopitaux',
                'db_table': 'Hopital',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Libelle du service ')),
                ('en_operation', models.BooleanField(default=False, verbose_name='En opération')),
                ('appareils', models.ManyToManyField(related_name='appareils', to='Sante.appareil', verbose_name='Appareil')),
                ('hopital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='Sante.hopital')),
            ],
            options={
                'verbose_name_plural': 'Services',
                'db_table': 'Service',
            },
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name="Nom de l'hopital ")),
                ('titre', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='photo-medecin/')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medecins', to='Sante.service')),
            ],
            options={
                'verbose_name_plural': 'Medecins',
                'db_table': 'Medecin',
            },
        ),
    ]
