# Generated by Django 5.0.2 on 2024-02-23 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sante', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='appareils',
        ),
        migrations.AddField(
            model_name='appareil',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='appareils', to='Sante.service', verbose_name='Appareil'),
            preserve_default=False,
        ),
    ]
